name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build Docker image
      run: |
        docker build -t my-python-app:latest ./pythonApp

    - name: Tag Docker image
      run: |
        docker tag my-python-app:latest 676655128572.dkr.ecr.us-east-1.amazonaws.com/my-python-app:latest

    - name: Push Docker image to ECR
      run: |
        docker push 676655128572.dkr.ecr.us-east-1.amazonaws.com/my-python-app:latest

    - name: Deploy to Docker Container
      run: |
        docker run --rm 676655128572.dkr.ecr.us-east-1.amazonaws.com/my-python-app:latest ./deploy.sh
